"""
05_export_dashboard_json.py

Joins all the CSVs generated by 02_compute_metrics.py, 03_compute_h2h.py
and 04_compute_match_load.py, and exports them to a JS file with several
named arrays (not a single flat rawData like the original template,
because our data lives at different "grains": per match, per player,
per player pair, per week).

Generates output/tennisData.js with these exports:
  - players               list of unique player names, for the selector
  - eloCurrent             current Elo ranking
  - eloHistory             Elo evolution over time
  - playerSurfaceStats     win rate by player and surface
  - serveReturnByPlayer    serve/return stats averaged by player
  - h2hOverall             head-to-head between player pairs
  - h2hBySurface           head-to-head broken down by surface
  - matchesPerPeriod       match load by player and week/month
  - restDaysPerformance    win rate by days of rest (buckets)

Usage:
    python 05_export_dashboard_json.py
"""
import json
from pathlib import Path

import numpy as np
import pandas as pd

OUT_DIR = Path(__file__).resolve().parent.parent / "output"

# Besides saving to output/ (as a record/backup), we write directly
# into the frontend's src/ folder, so there's no manual copy step each
# time. If that folder doesn't exist (e.g. you renamed tennis-frontend),
# skip it with a warning instead of failing.
FRONTEND_SRC_DIR = Path(__file__).resolve().parent.parent / "tennis-frontend" / "src"


def read_csv_safe(name: str, **kwargs) -> pd.DataFrame:
    path = OUT_DIR / name
    if not path.exists():
        print(f"  warning: couldn't find {name}, skipping from export")
        return pd.DataFrame()
    return pd.read_csv(path, **kwargs)


def to_records(df: pd.DataFrame) -> list:
    """Converts a DataFrame to a JSON-ready list of dicts: NaN -> None,
    dates -> ISO string."""
    if df.empty:
        return []
    df = df.copy()
    for col in df.columns:
        if pd.api.types.is_datetime64_any_dtype(df[col]):
            df[col] = df[col].dt.strftime("%Y-%m-%d")
    df = df.replace({np.nan: None})
    return df.to_dict(orient="records")


def player_serve_return_stats() -> pd.DataFrame:
    """Averages the serve/return metrics (already computed per match in
    02_compute_metrics.py) at the player level. This is reshaping, not
    a new metric -- the w_*/l_* columns already exist in
    matches_with_metrics.csv."""
    matches = read_csv_safe("matches_with_metrics.csv")
    if matches.empty:
        return pd.DataFrame()

    return _aggregate_serve_return(matches)


def player_serve_return_stats_by_year() -> pd.DataFrame:
    """Same as player_serve_return_stats but also broken down by year, so
    the frontend can filter by date range (same pattern as
    playerSurfaceStatsByYear)."""
    matches = read_csv_safe("matches_with_metrics.csv", parse_dates=["match_date"])
    if matches.empty:
        return pd.DataFrame()

    matches = matches.dropna(subset=["match_date"]).copy()
    matches["year"] = matches["match_date"].dt.year
    return _aggregate_serve_return(matches, extra_group_cols=["year"])


def _aggregate_serve_return(matches: pd.DataFrame, extra_group_cols=None) -> pd.DataFrame:
    extra_group_cols = extra_group_cols or []
    extra_cols = [c for c in extra_group_cols if c in matches.columns]

    wins = matches[[
        "winner_name", "w_1st_in_pct", "w_1st_win_pct", "w_2nd_win_pct",
        "w_bp_saved_pct", "w_ace", "w_df", "winner_dominance_ratio", *extra_cols,
    ]].rename(columns={
        "winner_name": "player", "w_1st_in_pct": "first_in_pct",
        "w_1st_win_pct": "first_win_pct", "w_2nd_win_pct": "second_win_pct",
        "w_bp_saved_pct": "bp_saved_pct", "w_ace": "aces", "w_df": "double_faults",
        "winner_dominance_ratio": "dominance_ratio",
    })

    losses = matches[[
        "loser_name", "l_1st_in_pct", "l_1st_win_pct", "l_2nd_win_pct",
        "l_bp_saved_pct", "l_ace", "l_df", *extra_cols,
    ]].rename(columns={
        "loser_name": "player", "l_1st_in_pct": "first_in_pct",
        "l_1st_win_pct": "first_win_pct", "l_2nd_win_pct": "second_win_pct",
        "l_bp_saved_pct": "bp_saved_pct", "l_ace": "aces", "l_df": "double_faults",
    })
    losses["dominance_ratio"] = np.nan  # only computed for the winner

    combined = pd.concat([wins, losses], ignore_index=True)
    group_cols = ["player"] + extra_cols
    agg = combined.groupby(group_cols).agg(
        matches=("player", "size"),
        first_in_pct=("first_in_pct", "mean"),
        first_win_pct=("first_win_pct", "mean"),
        second_win_pct=("second_win_pct", "mean"),
        bp_saved_pct=("bp_saved_pct", "mean"),
        aces_avg=("aces", "mean"),
        double_faults_avg=("double_faults", "mean"),
        dominance_ratio_avg=("dominance_ratio", "mean"),
    ).reset_index()

    for col in ["first_in_pct", "first_win_pct", "second_win_pct", "bp_saved_pct", "dominance_ratio_avg"]:
        agg[col] = agg[col].round(3)
    for col in ["aces_avg", "double_faults_avg"]:
        agg[col] = agg[col].round(1)

    return agg


def build_players_list(elo_current: pd.DataFrame) -> list:
    """List of players with their tour, sorted by Elo descending (it
    already comes sorted this way from compute_elo in
    02_compute_metrics.py)."""
    if elo_current.empty:
        return []
    cols = ["player"] + (["tour"] if "tour" in elo_current.columns else [])
    return to_records(elo_current[cols])


def write_js_file(data: dict, out_path: Path):
    lines = [
        "// Auto-generated by 05_export_dashboard_json.py -- do not edit by hand.",
        "",
    ]
    for name, records in data.items():
        lines.append(f"export const {name} = {json.dumps(records, ensure_ascii=False)};")
        lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main():
    print("Reading CSVs from output/...")
    elo_current = read_csv_safe("elo_current.csv")
    elo_history = read_csv_safe("elo_history.csv", parse_dates=["date"])
    player_surface = read_csv_safe("player_surface_stats.csv")
    player_surface_by_year = read_csv_safe("player_surface_stats_by_year.csv")
    h2h_overall = read_csv_safe("h2h_overall.csv", parse_dates=["last_meeting_date"])
    h2h_surface = read_csv_safe("h2h_by_surface.csv")
    matches_period = read_csv_safe("matches_per_period.csv")
    rest_perf = read_csv_safe("rest_days_performance.csv")
    serve_return = player_serve_return_stats()
    serve_return_by_year = player_serve_return_stats_by_year()

    data = {
        "players": build_players_list(elo_current),
        "eloCurrent": to_records(elo_current),
        "eloHistory": to_records(elo_history),
        "playerSurfaceStats": to_records(player_surface),
        "playerSurfaceStatsByYear": to_records(player_surface_by_year),
        "serveReturnByPlayer": to_records(serve_return),
        "serveReturnByPlayerYear": to_records(serve_return_by_year),
        "h2hOverall": to_records(h2h_overall),
        "h2hBySurface": to_records(h2h_surface),
        "matchesPerPeriod": to_records(matches_period),
        "restDaysPerformance": to_records(rest_perf),
    }

    for name, records in data.items():
        print(f"  {name}: {len(records):,} records")

    out_path = OUT_DIR / "tennisData.js"
    write_js_file(data, out_path)
    print(f"\nSaved to {out_path}")

    if FRONTEND_SRC_DIR.exists():
        frontend_path = FRONTEND_SRC_DIR / "tennisData.js"
        write_js_file(data, frontend_path)
        print(f"Also copied directly to {frontend_path}")
        print("(no need to copy it by hand -- Vite should hot-reload automatically)")
    else:
        print(
            f"\nwarning: couldn't find {FRONTEND_SRC_DIR} -- copy tennisData.js "
            "by hand to the src/ folder of your React project."
        )


if __name__ == "__main__":
    main()