"""
05_export_dashboard_json.py

Joins all the CSVs generated by 02_compute_metrics.py, 03_compute_h2h.py
and 04_compute_match_load.py, and exports them to a single JSON file
with several named top-level keys (not a single flat rawData like the
original template, because our data lives at different "grains": per
match, per player, per player pair, per week).

Generates output/tennisData.json with these top-level keys:
  - players               list of unique player names, for the selector
  - eloCurrent             current Elo ranking
  - eloHistory             Elo evolution over time
  - playerSurfaceStats     win rate by player and surface
  - serveReturnByPlayer    serve/return stats averaged by player
  - h2hOverall             head-to-head between player pairs
  - h2hBySurface           head-to-head broken down by surface
  - matchesPerPeriod       match load by player and week/month
  - restDaysPerformance    win rate by days of rest (buckets)

We export JSON, not a .js module with `export const` statements like
early versions of this script did. A .js file has to be parsed by
Vite/esbuild as JavaScript (build an AST for the whole thing) every time
the dev server starts, and for an array with hundreds of thousands of
records that blew past Node's default heap and crashed with an
out-of-memory error -- even after cutting the file down to ~80 MB with
the player filter below. A .json file placed in the frontend's public/
folder is served as-is and fetched at runtime with `fetch()`, which the
browser parses natively -- much cheaper, and it doesn't bloat the
production bundle either.

Filters out players with fewer than MIN_MATCHES career matches before
building any export. Without this, the export includes every player who
ever appears in the dataset (7,000+, most with a handful of matches),
which blows up combinatorial exports like h2hOverall/h2hBySurface
(pairs of players). Note this filtering is now also done earlier, in
01_fetch_atp_matches.py -- keeping it here too is a harmless safety net
in case the two scripts are ever run with different thresholds.

Usage:
    python 05_export_dashboard_json.py
    python 05_export_dashboard_json.py --min-matches 30
"""
import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

OUT_DIR = Path(__file__).resolve().parent.parent / "output"
DATA_DIR = Path(__file__).resolve().parent.parent / "data"

DEFAULT_MIN_MATCHES = 50

# Besides saving to output/ (as a record/backup), we write directly
# into the frontend's public/ folder, so there's no manual copy step
# each time and Vite serves it as a static file at /tennisData.json
# (fetched at runtime, not bundled/parsed as JS). If that folder doesn't
# exist (e.g. you renamed tennis-frontend), skip it with a warning
# instead of failing.
FRONTEND_PUBLIC_DIR = Path(__file__).resolve().parent.parent / "tennis-frontend" / "public"


def read_csv_safe(name: str, base_dir: Path = OUT_DIR, **kwargs) -> pd.DataFrame:
    path = base_dir / name
    if not path.exists():
        print(f"  warning: couldn't find {name}, skipping from export")
        return pd.DataFrame()
    return pd.read_csv(path, **kwargs)


def to_records(df: pd.DataFrame) -> list:
    """Converts a DataFrame to a JSON-ready list of dicts: NaN -> None,
    dates -> ISO string."""
    if df.empty:
        return []
    df = df.copy()
    for col in df.columns:
        if pd.api.types.is_datetime64_any_dtype(df[col]):
            df[col] = df[col].dt.strftime("%Y-%m-%d")
    df = df.replace({np.nan: None})
    return df.to_dict(orient="records")


def player_serve_return_stats(matches: pd.DataFrame) -> pd.DataFrame:
    """Averages the serve/return metrics (already computed per match in
    02_compute_metrics.py) at the player level. This is reshaping, not
    a new metric -- the w_*/l_* columns already exist in
    matches_with_metrics.csv."""
    if matches.empty:
        return pd.DataFrame()

    return _aggregate_serve_return(matches)


def player_serve_return_stats_by_year(matches: pd.DataFrame) -> pd.DataFrame:
    """Same as player_serve_return_stats but also broken down by year, so
    the frontend can filter by date range (same pattern as
    playerSurfaceStatsByYear). Expects matches with match_date already
    parsed as datetime."""
    if matches.empty:
        return pd.DataFrame()

    matches = matches.dropna(subset=["match_date"]).copy()
    matches["year"] = matches["match_date"].dt.year
    return _aggregate_serve_return(matches, extra_group_cols=["year"])


def get_qualified_players(matches: pd.DataFrame, min_matches: int) -> set:
    """Player pool for the whole export: names that appear (as winner or
    loser) in at least min_matches career matches. Cuts the 7,000+
    all-time player list down to the ones worth showing in a portfolio
    dashboard, and keeps combinatorial exports (h2h pairs) from
    exploding."""
    if matches.empty:
        return set()
    counts = pd.concat([matches["winner_name"], matches["loser_name"]]).value_counts()
    return set(counts[counts >= min_matches].index)


def filter_players(df: pd.DataFrame, qualified: set, col: str = "player") -> pd.DataFrame:
    """Keeps only rows whose player (single column) is in the qualified set."""
    if df.empty or col not in df.columns:
        return df
    return df[df[col].isin(qualified)]


def filter_player_pairs(df: pd.DataFrame, qualified: set) -> pd.DataFrame:
    """Keeps only rows where BOTH player_a and player_b are qualified --
    for h2h exports, which are keyed by pairs, not single players."""
    if df.empty or "player_a" not in df.columns or "player_b" not in df.columns:
        return df
    return df[df["player_a"].isin(qualified) & df["player_b"].isin(qualified)]


def _aggregate_serve_return(matches: pd.DataFrame, extra_group_cols=None) -> pd.DataFrame:
    extra_group_cols = extra_group_cols or []
    extra_cols = [c for c in extra_group_cols if c in matches.columns]

    wins = matches[[
        "winner_name", "w_1st_in_pct", "w_1st_win_pct", "w_2nd_win_pct",
        "w_bp_saved_pct", "w_ace", "w_df", "winner_dominance_ratio", *extra_cols,
    ]].rename(columns={
        "winner_name": "player", "w_1st_in_pct": "first_in_pct",
        "w_1st_win_pct": "first_win_pct", "w_2nd_win_pct": "second_win_pct",
        "w_bp_saved_pct": "bp_saved_pct", "w_ace": "aces", "w_df": "double_faults",
        "winner_dominance_ratio": "dominance_ratio",
    })

    losses = matches[[
        "loser_name", "l_1st_in_pct", "l_1st_win_pct", "l_2nd_win_pct",
        "l_bp_saved_pct", "l_ace", "l_df", *extra_cols,
    ]].rename(columns={
        "loser_name": "player", "l_1st_in_pct": "first_in_pct",
        "l_1st_win_pct": "first_win_pct", "l_2nd_win_pct": "second_win_pct",
        "l_bp_saved_pct": "bp_saved_pct", "l_ace": "aces", "l_df": "double_faults",
    })
    losses["dominance_ratio"] = np.nan  # only computed for the winner

    combined = pd.concat([wins, losses], ignore_index=True)
    group_cols = ["player"] + extra_cols
    agg = combined.groupby(group_cols).agg(
        matches=("player", "size"),
        first_in_pct=("first_in_pct", "mean"),
        first_win_pct=("first_win_pct", "mean"),
        second_win_pct=("second_win_pct", "mean"),
        bp_saved_pct=("bp_saved_pct", "mean"),
        aces_avg=("aces", "mean"),
        double_faults_avg=("double_faults", "mean"),
        dominance_ratio_avg=("dominance_ratio", "mean"),
    ).reset_index()

    for col in ["first_in_pct", "first_win_pct", "second_win_pct", "bp_saved_pct", "dominance_ratio_avg"]:
        agg[col] = agg[col].round(3)
    for col in ["aces_avg", "double_faults_avg"]:
        agg[col] = agg[col].round(1)

    return agg


def build_players_list(elo_current: pd.DataFrame) -> list:
    """List of players with their tour, sorted by Elo descending (it
    already comes sorted this way from compute_elo in
    02_compute_metrics.py)."""
    if elo_current.empty:
        return []
    cols = ["player"] + (["tour"] if "tour" in elo_current.columns else [])
    return to_records(elo_current[cols])


def player_best_rank(matches: pd.DataFrame) -> pd.DataFrame:
    """Best (lowest) official ATP/WTA rank a player held at the time of
    any match in the dataset -- their career-best ranking, not their
    ranking today. winner_rank/loser_rank are the ranking each player
    held AT THE TIME of that specific match (not looked up separately),
    so the min across all their matches is their career-best rank. Used
    by the frontend to recognize past top players who don't have a
    current ranking anymore (retired), e.g. to build a "current top 50
    OR ever reached top 10" filter."""
    if matches.empty or "winner_rank" not in matches.columns or "loser_rank" not in matches.columns:
        return pd.DataFrame(columns=["player", "best_rank"])

    wins = matches[["winner_name", "winner_rank"]].rename(
        columns={"winner_name": "player", "winner_rank": "rank"}
    )
    losses = matches[["loser_name", "loser_rank"]].rename(
        columns={"loser_name": "player", "loser_rank": "rank"}
    )
    all_appearances = pd.concat([wins, losses], ignore_index=True).dropna(subset=["rank"])
    if all_appearances.empty:
        return pd.DataFrame(columns=["player", "best_rank"])

    best = all_appearances.groupby("player")["rank"].min().reset_index()
    best = best.rename(columns={"rank": "best_rank"})
    best["best_rank"] = best["best_rank"].astype(int)
    return best


def write_json_file(data: dict, out_path: Path):
    out_path.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")


def downsample_elo_history_to_quarterly(elo_history: pd.DataFrame) -> pd.DataFrame:
    """Colapsa eloHistory a un punto por jugador por trimestre (el ultimo
    valor de ese trimestre) en vez de un punto por partido. El grafico de
    Player Overview YA hace exactamente esta misma reduccion en el
    navegador (se queda con el ultimo Elo de cada trimestre y descarta el
    resto) -- asi que mandar el detalle partido a partido es puro peso
    extra sin ninguna ganancia visual. Para un jugador con una carrera
    larga (cientos de partidos), esto puede reducir sus filas 5-10x, que
    es exactamente donde se estaba yendo la mayor parte del tamaño del
    archivo (--min-matches mas alto saca JUGADORES, no reduce cuantos
    partidos tiene cada uno que sobrevive el filtro)."""
    if elo_history.empty:
        return elo_history
    m = elo_history.sort_values("date").copy()
    m["quarter"] = m["date"].dt.to_period("Q").astype(str)
    out = m.groupby(["player", "quarter"], as_index=False).last()
    return out[["player", "date", "elo"]]


def downsample_matches_per_period_to_quarterly(matches_per_period: pd.DataFrame) -> pd.DataFrame:
    """Mismo criterio que downsample_elo_history_to_quarterly, pero para
    matchesPerPeriod: Match Load & Fatigue SUMA los partidos semanales
    dentro de cada trimestre en el navegador para armar el grafico "Matches
    per Quarter" -- nunca se muestra el detalle semana a semana. Sumamos
    nosotros ese mismo trimestre en el pipeline (52 semanas/anio -> 4
    trimestres/anio, ~13x menos filas) y el frontend, al recibir datos que
    ya vienen por trimestre, simplemente "suma" cada fila consigo misma --
    mismo resultado final, muchas menos filas viajando.
    Requiere el cambio de una linea en MatchLoad.jsx (period_type "week"
    -> "quarter" en el filtro), documentado en el mensaje al usuario."""
    if matches_per_period.empty:
        return matches_per_period
    weekly = matches_per_period[matches_per_period["period_type"] == "week"].copy()
    other = matches_per_period[matches_per_period["period_type"] != "week"]
    if weekly.empty:
        return matches_per_period

    weekly["start_date"] = pd.to_datetime(weekly["period"].str.split("/").str[0])
    weekly["quarter_period"] = weekly["start_date"].dt.to_period("Q")

    agg = weekly.groupby(["player", "quarter_period"], as_index=False).agg(
        matches=("matches", "sum"),
        gs_matches=("gs_matches", "sum"),
    )
    agg["period"] = agg["quarter_period"].apply(
        lambda p: f"{p.start_time.date()}/{p.end_time.date()}"
    )
    agg["period_type"] = "quarter"
    agg = agg[["player", "period", "matches", "gs_matches", "period_type"]]

    return pd.concat([agg, other], ignore_index=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--min-matches", type=int, default=DEFAULT_MIN_MATCHES,
        help="Minimum career matches (as winner+loser) for a player to be "
             "included in the export. Default: %(default)s.",
    )
    args = parser.parse_args()

    print("Reading CSVs from output/...")
    elo_current = read_csv_safe("elo_current.csv")
    elo_history = read_csv_safe("elo_history.csv", parse_dates=["date"], date_format="%Y-%m-%d")
    elo_history = downsample_elo_history_to_quarterly(elo_history)
    player_surface = read_csv_safe("player_surface_stats.csv")
    player_surface_by_year = read_csv_safe("player_surface_stats_by_year.csv")
    player_tourney_by_year = read_csv_safe("player_tourney_stats_by_year.csv")
    player_titles = read_csv_safe("player_titles.csv")
    h2h_overall = read_csv_safe("h2h_overall.csv", parse_dates=["last_meeting_date"], date_format="%Y-%m-%d")
    # longest_match_date only exists if 03_compute_h2h.py found "minutes"
    # data to work with -- parse it after loading (not via parse_dates
    # above) so this doesn't blow up on older h2h_overall.csv files that
    # don't have the column yet.
    if not h2h_overall.empty and "longest_match_date" in h2h_overall.columns:
        h2h_overall["longest_match_date"] = pd.to_datetime(
            h2h_overall["longest_match_date"], format="%Y-%m-%d", errors="coerce"
        )
    h2h_surface = read_csv_safe("h2h_by_surface.csv")
    h2h_year = read_csv_safe("h2h_by_year.csv")
    h2h_gs_finals_detail = read_csv_safe("h2h_gs_finals_detail.csv")
    matches_period = read_csv_safe("matches_per_period.csv")
    matches_period = downsample_matches_per_period_to_quarterly(matches_period)
    rest_perf = read_csv_safe("rest_days_performance.csv")
    rest_perf_by_player = read_csv_safe("rest_days_performance_by_player.csv")
    # rest_days_detail.csv (partido a partido) NO se exporta -- confirmado
    # que ningun componente del frontend lo usa (grep -rn "restDaysDetail"
    # src/ no encuentra nada). restDaysPerformance/restDaysPerformanceByPlayer
    # ya traen los buckets pre-calculados que si se muestran en pantalla.
    # Era el segundo array mas pesado del JSON (300k+ filas a min-matches
    # bajos) sin aportar nada visible -- sacarlo es peso gratis.
    gs_editions = read_csv_safe("grand_slam_editions.csv")
    current_ranking = read_csv_safe("player_current_rank.csv", base_dir=DATA_DIR)

    # matches_with_metrics.csv is the source both for the serve/return
    # aggregations AND for deciding which players make the cut -- read it
    # once here and reuse it for both, instead of reading it twice.
    matches_raw = read_csv_safe("matches_with_metrics.csv", parse_dates=["match_date"], date_format="%Y-%m-%d")

    qualified = get_qualified_players(matches_raw, args.min_matches)
    print(f"\nPlayer filter: >= {args.min_matches} career matches -> "
          f"{len(qualified):,} qualified players (out of "
          f"{elo_current['player'].nunique() if not elo_current.empty else 0:,} total)\n")

    serve_return = player_serve_return_stats(matches_raw)
    serve_return_by_year = player_serve_return_stats_by_year(matches_raw)
    best_rank = player_best_rank(matches_raw)

    # Apply the player filter to every export. h2h exports are keyed by
    # pairs, so both players in the pair need to qualify; everything else
    # is a single "player" column.
    elo_current = filter_players(elo_current, qualified)
    elo_history = filter_players(elo_history, qualified)
    player_surface = filter_players(player_surface, qualified)
    player_surface_by_year = filter_players(player_surface_by_year, qualified)
    player_tourney_by_year = filter_players(player_tourney_by_year, qualified)
    player_titles = filter_players(player_titles, qualified)
    serve_return = filter_players(serve_return, qualified)
    serve_return_by_year = filter_players(serve_return_by_year, qualified)
    h2h_overall = filter_player_pairs(h2h_overall, qualified)
    h2h_surface = filter_player_pairs(h2h_surface, qualified)
    h2h_year = filter_player_pairs(h2h_year, qualified)
    h2h_gs_finals_detail = filter_player_pairs(h2h_gs_finals_detail, qualified)
    matches_period = filter_players(matches_period, qualified)
    rest_perf_by_player = filter_players(rest_perf_by_player, qualified)
    gs_editions = filter_players(gs_editions, qualified)
    current_ranking = filter_players(current_ranking, qualified)
    best_rank = filter_players(best_rank, qualified)
    # restDaysPerformance is aggregated across all players (rest-day
    # buckets, not per-player rows), so it's intentionally left unfiltered.

    data = {
        "players": build_players_list(elo_current),
        "eloCurrent": to_records(elo_current),
        "eloHistory": to_records(elo_history),
        "playerSurfaceStats": to_records(player_surface),
        "playerSurfaceStatsByYear": to_records(player_surface_by_year),
        "playerTourneyStatsByYear": to_records(player_tourney_by_year),
        "playerTitles": to_records(player_titles),
        "serveReturnByPlayer": to_records(serve_return),
        "serveReturnByPlayerYear": to_records(serve_return_by_year),
        "h2hOverall": to_records(h2h_overall),
        "h2hBySurface": to_records(h2h_surface),
        "h2hByYear": to_records(h2h_year),
        "h2hGsFinalsDetail": to_records(h2h_gs_finals_detail),
        "matchesPerPeriod": to_records(matches_period),
        "restDaysPerformance": to_records(rest_perf),
        "restDaysPerformanceByPlayer": to_records(rest_perf_by_player),
        "grandSlamEditions": to_records(gs_editions),
        "bestCareerRank": to_records(best_rank),
        "currentRanking": to_records(current_ranking),
    }

    for name, records in data.items():
        print(f"  {name}: {len(records):,} records")

    out_path = OUT_DIR / "tennisData.json"
    write_json_file(data, out_path)
    print(f"\nSaved to {out_path}")

    if FRONTEND_PUBLIC_DIR.exists():
        frontend_path = FRONTEND_PUBLIC_DIR / "tennisData.json"
        write_json_file(data, frontend_path)
        print(f"Also copied directly to {frontend_path}")
        print("(reload the page in the browser -- no dev server restart needed)")
    else:
        print(
            f"\nwarning: couldn't find {FRONTEND_PUBLIC_DIR} -- copy "
            "tennisData.json by hand to the public/ folder of your React project."
        )


if __name__ == "__main__":
    main()